name: trigger jenkins job
on:
  pull_request_target:
    branches:
      - master
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@v0.0.2
      with:
        url: "http://localhost:8080/"
        user: "meenakshi-rv"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "Crown_JenkinsTest"
