name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@v0.0.2
      with:
        url: "https://02b6-203-214-84-2.au.ngrok.io/"
        user: "meenakshi-rv"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "Crown_JenkinsTest"
